project:
  type: website

website:
  title: "Tom Sasani"

  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: pubs.qmd
      - text: "Talks"
        file: talks.qmd
      - text: "Teaching"
        file: teaching.qmd
      - sidebar:tutorials
      - sidebar:cv

    right: 
      - icon: twitter
        href: https://twitter.com/tomsasani
      - icon: github
        href: https://github.com/tomsasani
  
  sidebar:

    - id: tutorials
      title: "Tutorials"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - href: snakemake.qmd
        - href: gatk.qmd

    - id: cv 
      title: "CV/Resume"
      style: "docked"
      background: light 
      collapse-level: 2
      contents:
        - text: "CV"
          href: vitae/sasani_thomas_cv.pdf
        - text: "Resume"
          href: vitae/sasani_thomas_resume.pdf

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      #light: cosmo
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true



