project:
  type: website

execute:
  freeze: auto

website:
  title: "Tom Sasani"

  navbar:
    background: "#C1DBDA"
    left:
      - text: "Home"
        file: index.qmd
      # - text: "Research"
      #   file: research.qmd
      - text: "Publications"
        file: pubs.qmd
      - text: "Talks"
        file: talks.qmd
      - text: "Teaching"
        file: teaching.qmd
      - sidebar:notes
      # - sidebar:ml-reading-group
      - sidebar:cv

    right: 
      - icon: twitter
        href: https://twitter.com/tomsasani
      - icon: github
        href: https://github.com/tomsasani
  
  sidebar:

    - id: notes
      title: "Research notes"
      style: "docked"
      background: "light"
      collapse-level: 2
      contents: 
        - href: notes/tiny_transformers.qmd
        - href: notes/gatk.qmd
        - href: notes/snakemake.qmd

    - id: cv 
      title: "CV/Resume"
      style: "docked"
      collapse-level: 2
      contents:
        - text: "CV"
          href: vitae/sasani_thomas_cv.pdf
        - text: "Resume"
          href: vitae/sasani_thomas_resume_longform.pdf

    # - id: ml-reading-group
    #   title: "ML reading group"
    #   style: "docked"
    #   background: "light"
    #   collapse-level: 2
    #   contents: 
    #     - href: ml_reading_group/2024_intro.qmd

format:
  html:
    theme:
      # light: [default, theme.scss]
      # - default
      - theme.scss
      # dark: [default, theme-dark.scss]
      # dark: default
    mainfont: "Puritan"
    code-copy: true
    code-overflow: wrap
    toc: true



