---
title: ""
from: markdown
toc: true
date: last-modified
date-format: "YYYY-MM-DD"
---

## <span class="span_generic">Lab expectations</span>

Credit to [Jeff Ross-Ibarra](https://rilab.ucdavis.edu/index.html), from whom I've borrowed much of this content.

*These expectations are subject to change, and I anticipate soliciting feedback from all lab members via annual, anonymous lab surveys.*

---

**Long story short:**

* take care of your mental and physical health
* be a kind, courteous, and respectful colleague & mentor 
* do rigorous and reproducible science
* communicate effectively in papers, grants, and presentations

---

### The basics

*Your well-being comes first.*

I want everyone in the lab to be an active contributor (to your own projects and to the lab as a whole), but that should never come at the expense of your mental and physical health. 
Please stay home if you feel ill.
And when "life happens," just let me know — we can almost certainly work something out.

*Treat others with respect and generosity.*

We strive to maintain an inclusive, collegial, and friendly lab environment.
Inappropriate comments and behavior will not be tolerated.

*Do rigorous, reproducible science.*

Code and experimental methods should be carefully documented and published alongside every manuscript.
Datasets should be easily accessible and amenable to re-analysis.
Papers should always be uploaded to preprint servers.

---

### Work hours

As a primarily computational lab, we have some flexibility in terms of where and when we work.
However, I believe that in-person communication and collaboration are vital parts of the scientific process.
We generally expect lab members to be present during normal business hours (9-5pm, Monday through Friday). 
You are not expected to work in the evenings or on the weekends, though there may be rare occasions when an experiment requires you to come in at an odd hour.
It's important that you take time off for personal life, vacations, etc. 
Just notify me if you will be absent for ≥1 day, and let me know in advance of any extended leave.

### Seminars, journal clubs, and conferences

Attendance at regular weekly lab meetings is expected of all lab members. 
Lab members are strongly encouraged to attend departmental seminars, journal clubs, and similar events.
Lab members are expected to attend other lab members' practice talks (for conference presentations, departmental seminars, thesis defenses, etc.)

Everyone is encouraged to attend at least one conference a year. 
If possible, trainees are encouraged apply for external sources of funding to help cover travel expenses. 
Regardless, I will fund registration and travel to at least one conference per year for each member of the lab (on the condition that you are presenting a poster or talk).
Depending on meeting locations/costs, I'm happy to fund attendance at >1 conferences. 
Please provide ample time before submission deadlines for me to review abstracts and posters, and for practicing talks.

### Authorship

We follow the [ICJME rules](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html) for authorship:

1. Substantial contributions to the conception or design of the work; or the acquisition, analysis, or interpretation of data for the work; **AND**
2. Drafting the work or revising it critically for important intellectual content; **AND**
3. Final approval of the version to be published; **AND**
4. Agreement to be accountable for all aspects of the work in ensuring that questions related to the accuracy or integrity of any part of the work are appropriately investigated and resolved. Projects evolve over time and authorship inclusion and author order will be re-evaluated accordingly.

### Open science

I expect all lab members to conduct open, reproducible science.
The term "open science" is very broadly defined, but for our purposes this means:

* Maintaining code for computational projects in open-source GitHub repos 
* Publishing a preprint as soon as a manuscript is ready for submission
* Publishing data as soon as possible, *in a format that makes it easy for collaborators and peers to reproduce your findings*

<!-- ### Publishing policies

In general, we aim to publish our work in peer-reviewed society journals (those maintained by professional scientific societies, including the Genetics Society of America, Society for Molecular Biology and Evolution, etc.).
All journals charge substantial fees for publication.
Unlike for-profit publishers, though, society journals generally use those fees to fund grants, travel awards, etc. for the community.
We also publish in open-access journals, including *eLife* and *PLoS*. -->


### Expectations by lab member stage

#### Postdocs/senior Ph.D students

---

**My responsibilities** to you:

* Assist with identifying and writing postdoctoral fellowships.
* Develop project ideas, including independent projects that can be taken with the postdoc.
* Interpret results.
* Proof-read manuscripts.
* Discuss future career goals (e.g., do you want to teach, go into academia, industry, continue in research?), and plan ways to facilitate these goals.
* Meet weekly to discuss progress & pitfalls.

**Your responsibilities**:

* Prepare for our regular progress/pitfalls meetings.
* Write and submit manuscripts.
* Proof-read manuscripts from other lab members.
* Apply for external funding (either individual postdoc fellowships or contributing to larger lab grant writing).
* Maintain a set of lab notes, including directories of data, annotated code & versions, detailed methods.
* Participate in general lab responsibilities (keep common areas tidy, take turns hosting visitors, etc.). 
* Participate in talk rehearsals of your colleagues.

#### Junior Ph.D students

---

**My responsibilities** to you:

* Develop project ideas.
* Interpret results.
* Proof-read and contribute to writing of thesis, abstracts and manuscripts.
* Discuss future career goals (e.g., do you want to teach, go into academia, continue in research?), and plan ways to facilitate these goals.
* Meet weekly to discuss progress and pitfalls.

**Your responsibilities**:

* Prepare for our regular progress/pitfalls meetings.
* Write and submit manuscripts. 
    * On average, I expect most students to produce three publications over the course of their PhD, including at least one first-author paper.
* Maintain a set of lab notes, including directories of data, annotated code & versions, detailed methods. 
* Write thesis in due time.
* Proof-read manuscripts from other lab members. 
* Participate in talk rehearsals of your colleagues.
* Participate in general lab responsibilities (keep common areas tidy, take turns hosting visitors, etc.). 
* Present multiple research talks/posters at conferences over the course of your time in the lab. You are encouraged to do so annually, but this isn’t always possible.

