---
title: "Keeping your genome intact"
toc: true
---

### We're all mutants, more or less

Humans are pretty good at passing down our genetic material from generation to generation. We all inherit about three billion [nucleotides]() from each of our parents, which are neatly packaged into twenty-three chromosomes. [Nucleotides are the four molecules that comprise <u>d</u>eoxyribo<u>n</u>ucleic <u>a</u>cid, or DNA. We represent them as "letters" in the genetic code: `A`, `T`, `C`, and `G`.]{.aside} Before those chromosomes find their way into a fertilized embryo (a.k.a., the future you), they have to be precisely copied and pasted into a sperm or egg cell. If a mistake happens during the copying process, or if a nucleotide gets damaged, a *de novo* mutation will be passed on to the next generation [In Latin, *de novo* literally means "of new."]{.aside}. In other words, you might inherit a `C` that should have been a `T`, or an `A` instead of a `G`.

Every one of our genomes contains about 70-100 *de novo* mutations. [Lots of studies have estimated the number of new mutations that occur each generation. We usually come up with these estimates by comparing the DNA of parents and their children. We iterate through the billions of nucleotides in the child's DNA sequence and ask if there are "letters" that don't match the corresponding letter in either parent's genome sequence.]{.aside} Some of those mutations were the result of a problem with the "copy-and-paste" operation (called *replication*) that happened in our parents' germline cells, and some happened because our parents' DNA was damaged. The DNA in our cells is under constant threat; UV light from the sun can break up the bonds that hold nucleotides together, tobacco smoke can cause a buildup of damaging chemical modifications, and there may even be defects in the machinery that replicates our DNA to begin with. With that in mind, an error rate of about 0.00000001 per generation ($\frac{70}{6,000,000,000}$) doesn't sound so bad.

### It takes a village (to replicate DNA)

Copying a complete genome sequence and packaging it up within a sperm or egg cell is an outrageously complicated process. [Jedidiah Carlson put together a really wonderful Twitter thread that describes just how incredible DNA replication is. I highly encourage you to check it out [here.](https://twitter.com/JedMSP/status/967879091121807361)]{.aside} Within a single cell, our DNA strands are tightly wound around proteins called *histones* and crammed inside of a miniscule part of the cell called the *nucleus*. It's pretty close quarters in there; the nucleus inside of a typical human cell has a diameter of about 6 micrometers, or about 1/10th the width of a human hair. Within that extraordinarily tiny compartment, every cell stores about *6 linear feet* of DNA. 

Imagine that you're a cell that needs to make a copy of your DNA. You'll need to unwind 6 feet worth of nucleotides, stored on 23 different pairs of chromosomes, each of which is a rat's nest of twisted genetic material. Then, you'll need to make a high-fidelity copy of every letter in the 6-billion-letter long sequence, making sure that you don't miss a spot or put a `C` where a `G` should be. (Or wait, maybe it was supposed to be an `A`? Too late, you just introduced a *de novo* mutation.) And watch out for radiation, free radicals, and who knows what else that is trying to shatter the DNA you haven't gotten around to copying yet. In the end, it takes a village of proteins to orchestrate this process, like a Xerox machine with hundreds of unique, essential parts. What happens if one of those parts breaks? If you've used a Xerox machine before, you probably know the answer, and it's not good news.

### Mutations beget mutations

We often refer to these broken pieces of machinery as "mutator alleles" &mdash; basically, defective versions of the proteins that maintain the integrity of our DNA. [More specifically, a mutator allele is a version of a *gene* that encodes a protein, but the semantics aren't super important here.]{.aside} In a recent paper, I developed a new method to detect mutator alleles, and used it to discover not one, but two "mutators" lurking in the genomes of laboratory mice. The method is pretty simple: basically, I try to identify mice with more *de novo* mutations than others. If the mice with extra mutations also have a different version of a DNA replication or repair protein than the mice with "normal" levels of mutation, we might be able to pinpoint the former as a *mutator allele*. 

Identifying mutator alleles is pretty challenging. One reason is that individuals with mutator alleles are predicted to have less [fitness]() than those with "normal" alleles. [Fitness is essentially an individual's lifetime reproductive success (how many offspring it has). Fewer offspring means fewer chances to pass down your genetic material, and more relevant to this discussion, fewer chances to pass down a mutator allele to the next generation.]{.aside} As a result, those mutator alleles are quickly purged from populations. Another reason is that our genomes are actually pretty resilient when a piece of the DNA proofreading machinery breaks. In the study we recently published, mice with the most severe mutator allele only passed down about 2% more *de novo* mutations than those with normal alleles. That's a super small effect. So, how did we detect it?

### The spectrum of mutation

Our major innovation was to look for the signatures of mutator alleles on the *spectrum* of *de novo* mutation. Like I said before, the number of *de novo* mutations only increased by about 2% in the mice with the most severe mutator allele. But not all *de novo* mutations are created equal. There are 4 nucleotides at every position in a genome sequence, and each of those nucleotides could theoretically be mutated to any of the other 3. For example, a `C` could mutate to a `G`, `T`, or `A`. As it turns out, some of the machinery that maintains genome integrity is uniquely good at preventing specific types of mutations. Some genes make proteins that pretty much only prevent `C` $\to$ `A` mutations, for example. We refer to all of the various possible mutation types as the [spectrum]() of mutation, and it can reveal a lot about the ways in which those mutations occurred. 

In our study, we specifically looked for mutator alleles that affected certain elements of the *mutation spectrum*, giving us a lot more power. Even though the mutator alleles we discovered increased the *overall* number of *de novo* mutations by about 2%, they increased the rate of one specific mutation type (`C` $\to$ `A`) by almost 50%. 




