---
title: "Publications"
from: markdown+emoji
---

Click :computer: to access associated code and :book: for PDFs.

## Preprints

Porubsky D, Dashnow H, **Sasani TA**, Logsdon GA, Hallast P, Noyes MD, Kronenberg ZN, Mokveld T, et al. A familial, telomere-to-telomere reference for human *de novo* mutation and
recombination from a four-generation pedigree (2024). [*bioRxiv*](https://www.biorxiv.org/content/10.1101/2024.08.05.606142v1)

Mokveld T, Dolzhenko E, Dashnow H, Nicholas TJ, **Sasani TA**, van der Sanden B, Jadhav B, Pedersen B, Kronenberg S, Tucci A, Sharp AJ, Quinlan AR, Gilissen C, Hoischen A, Eberle MA. TRGT-denovo: accurate detection of de novo tandem repeat mutations (2024). [*bioRxiv*](https://www.biorxiv.org/content/10.1101/2024.07.16.600745v1)

Xu K, Zhang Y, Baldwin-Brown J, **Sasani TA**, Phadnis N, Miller MP, Rog O. Decoding chromosome organization using CheC-PLS: chromosome conformation by proximity labeling and long-read sequencing (2024). [*bioRxiv*](https://doi.org/10.1101/2024.05.31.596864)

Ashbrook DG, **Sasani TA**, Maksimov M, Gunturkun MH, Ma N, Villani F, Ren Y, Rothschild D, Chen H, Lu L, Colonna V, Dumont B, Harris K, Gymrek M, Pritchard JK, Palmer AA, Williams RW. Private and sub-family specific mutations of founder haplotypes in the BXD family reveal phenotypic consequences relevant to health and disease (2022). [*bioRxiv.*](https://www.biorxiv.org/content/10.1101/2022.04.21.489063v1.abstract)

## Peer-reviewed Manuscripts

**Sasani TA**, Quinlan AR, Harris K. Epistasis between mutator alleles contributes to germline mutation rate variability in laboratory mice (2024). [*eLife.*](https://doi.org/10.7554/eLife.89096.3) \ [:computer:](https://github.com/quinlan-lab/proj-mutator-mapping)

Fixsen SM, Cone KR, Goldstein SA, **Sasani TA**, Quinlan AR, Rothenburg S, Elde NC. Poxviruses capture host genes by LINE-1 retrotransposition (2022). [*eLife.*](https://elifesciences.org/articles/63332) \ [:book:](pdfs/fixsen_elife_2022.pdf)

**Sasani TA**, Ashbrook DG, Beichman AC, Lu L, Palmer AA, Williams RW, Pritchard JK, Harris K. A natural mutator allele shapes mutation spectrum variation in mice (2022). [*Nature.*](https://www.nature.com/articles/s41586-022-04701-5) \ [:computer:](https://github.com/tomsasani/bxd_mutator_manuscript) \ [:book:](pdfs/sasani_nature_2022.pdf)

Belyeu JR*, **Sasani TA**\*, Pedersen BS, Quinlan AR. Unfazed: parent-of-origin detection for large and small de novo variants (2021). [*Bioinformatics.*](https://doi.org/10.1093/bioinformatics/btab454) \ [:computer:](https://github.com/jbelyeu/unfazed) \ [:book:](pdfs/belyeu_bioinfo_2021.pdf)

Wallace AD, **Sasani TA**, Swanier J, Gates B, Greenland J, Pedersen BP, Varley KT, Quinlan AR. CaBagE: a Cas9-based Background Elimination strategy for targeted, long-read DNA sequencing (2021). [*PLoS One.*](https://doi.org/10.1371/journal.pone.0241253) \ [:book:](pdfs/wallace_plos_2021.pdf)

Cawthon RM, Meeks HD, **Sasani TA***, Smith KR, Kerber RA, O'Brien E, Baird L, Dixon MM, Peiffer AP, Leppert MF, Quinlan AR, Jorde LB. Germline mutation rates in young adults predict longevity and reproductive lifespan (2020). [*Scientific Reports.*](https://www.nature.com/articles/s41598-020-66867-0) \ [:book:](pdfs/cawthon_scirep_2020.pdf)

**Sasani TA**, Pedersen BS, Gao Z, Baird L, Przeworski M, Jorde LB, Quinlan AR. Large, three-generation human families reveal post-zygotic mosaicism and variability in germline mutation accumulation (2019). [*eLife.*](https://elifesciences.org/articles/46922) \ [:computer:](https://github.com/quinlan-lab/ceph-dnm-manuscript) \ [:book:](pdfs/sasani_elife_2019.pdf)

Gao Z, Moorjani P, **Sasani TA**, Pedersen BP, Quinlan AR, Jorde LB, Amster G, Przeworski MP. Overlooked roles of DNA damage and maternal age in generating human germline mutations (2019). [*PNAS.*](https://www.pnas.org/content/116/19/9491.short) \  [:book:](pdfs/gao_pnas_2019.pdf)

**Sasani TA**\*, Cone KR\*, Quinlan AR, Elde NC. Long read sequencing reveals poxvirus evolution through rapid homogenization of gene arrays (2018). [*eLife.*](https://elifesciences.org/articles/35453) \ [:computer:](https://github.com/tomsasani/vacv-ont-manuscript) \ [:book:](pdfs/sasani_elife_2018.pdf)

Belyeu JR, Nicholas TJ, Pedersen BS, **Sasani TA**, Havrilla JM, Kravitz SN, Conway ME, Lohman BK, Quinlan AR, Layer RM. SV-plaudit: a cloud-based framework for manually curating thousands of structural variants (2018). [*GigaScience.*](https://academic.oup.com/gigascience/article/7/7/giy064/5026174) \ [:computer:](https://github.com/jbelyeu/SV-plaudit) \ [:book:](pdfs/belyeu_giga_2018.pdf)

Jain M\*, Koren S\*, Miga K\*, Quick J\*, Rand AC\*, **Sasani TA**\*, Tyson JR*, Beggs AD, Dilthey AT, Fiddes IT, Malla S, Marriott H, Nieto T, O’Grady J, Olsen HE, Pedersen BS, Rhie A, Richardson H, Quinlan AR, Snutch TP, Tee L, Paten B, Phillippy AM, Simpson JT, Loman NJ, Loose M. Nanopore sequencing and assembly of a human genome with ultra-long reads (2018). [*Nature Biotechnology.*](https://www.nature.com/articles/nbt.4060) \ [:book:](pdfs/jain_natbio_2018.pdf)

Feusier J, Witherspoon DJ, Watkins SW, Goubert C, **Sasani TA**, Jorde LB. Discovery of rare, diagnostic AluYb8/9 elements in diverse human populations (2017). [*Mobile DNA.*](https://mobilednajournal.biomedcentral.com/articles/10.1186/s13100-017-0093-0) \ [:book:](pdfs/feusier_mobdna_2017.pdf)

Piasecki BP, **Sasani TA**, Lessenger AT, Huth N, Farrell S. MAPK-15 is a ciliary protein required for PKD-2 localization and male mating behavior in Caenorhabditis elegans (2017). \ [*Cytoskeleton.*](https://doi.org/10.1002/cm.21387) \ [:book:](pdfs/piasecki_cytoskeleton_2017.pdf)

\* indicates equal contribution