---
title: "Talks"
---

## Invited Presentations

**Mapping mutator alleles in mice.** Lawrence University, Recent Advances in Biology Lecture Series (2021). *Virtual.*


**Mapping mutator alleles in mice.** Pritchard Lab Mini-conference (2021). *Virtual.*


**A wild-derived antimutator drives germline mutation spectrum differences in a genetically diverse murine family.** Columbia University, Przeworski Lab Meeting (2021). *Virtual.*


**Long read sequencing reveals poxvirus evolution through rapid homogenization of gene arrays.** Society for Molecular Biology and Evolution annual meeting (2019). *Manchester, UK.*


**Tracking adaptive structural variation during host-pathogen conflict.** London Calling, Oxford Nanopore Technologies annual meeting (2017). *London, UK.* [Viewable here.](https://vimeo.com/218946408)

## Contributed Presentations

**Fast and furious mutation at tandem repeats in a large, four-generation human family.** The Biology of Genomes (2025). *Cold Spring Harbor, NY*.

**Discovering epistasis between germline mutator alleles in mice.** The Biology of Genomes (2023). *Cold Spring Harbor, NY*.

**Directly measuring the dynamics of the human mutation rate by sequencing large, multi-generational pedigrees.** American Society of Human Genetics annual meeting (2018). Plenary presentation. *San Diego, CA.*


**Human immune defense mechanisms drive rapid genome evolution in vaccinia virus.** American Society of Human Genetics annual meeting (2017). Platform presentation. *Orlando, FL.*