---
#title: "My document"
format: 
  pdf:
    papersize: article
    # mainfont: Optima
    # sansfont: Optima
    geometry:
    - top=15mm
    - left=10mm
    - right=10mm
    - bottom=10mm
    - heightrounded
execute:
  freeze: auto
  echo: false
  warning: false
---

### Philosophy

I believe that scientific training should involve hands-on, practical laboratory work (to gain experience with scientific *practice*), critical engagement with primary literature (to understand the *process* of doing science, warts and all), and exposure to the ways in which genetics research can be interpreted after publication (to understand the potential *consequences* of that science).

Many of my undergraduate professors held regular "journal clubs," in which students were tasked with reading a scientific paper in advance of an in-classroom discussion. 
These exercises were invaluable to me as a student, and something I'd pursue as a faculty member at ##. 
These discussions make it clear that scientific knowledge is never "finished."
There is often room to reach different conclusions from the same data, and that even good science can be subject to valid criticism.
(were the data in Mendel's notebook a little too perfect, for example? []). 
What's more, at a time when misinformation is regularly peddled by "bad actors," it's more important than ever to have a toolbox for critically evaluating scientific claims. 

Classroom exercises could include lessons on how to identify data visualizations that distort or mis-represent underlying data, and 
Finally, I believe that critically engaging with scientific literature can reveal that science is not divorced from society and culture. 
For example, we can now see the unrecognized contributions of women and BIPOC to many seminal scientific results (for one recent example, see https://www.genetics.org/content/211/2/363).

It's also critical for students to build up a toolbox for combatting the misunderstandings and misinformation that often accompany studies of human genetics.
As the far right continues to co-opt everything from PCA plots to lactase persistence (cite Jed) to promote racist and pseudoscientific pablom, trainees must be prepared to defend against the misappropriation of genetic science. 
<!-- Complexity of human sex determination -->
Students should leave a biology or genetics course with both a foundational understanding of genes, cells, and organisms, as well as a toolbox to counter misinformation.

Finally, I've often found that learning abstract concepts in isolation can be more confusing than not. 
Learning often happens most effectively when the concepts are in service of a concrete goal or purpose. 
For example, in laboratory classes I would focus more on *methods* rather than specific outcomes. 
Students can (and should) write a lab report even if they end up with a final purified DNA concentration of $$0 \frac{ng}{uL}$$, if their gel electrophoresis image looks more "modern art" than "publication quality," or if the software application they've built has a handful of bugs and strange formatting issues. 
Similarly, in a computational biology class, there should be more of an emphasis on writing tests for individual units of code than on using those units to produce a great-looking final plot.

Finally, and especially at the undergraduate level, I think it's important to remember that a degree in science does not necessarily mean that students will go on to obtain terminal degrees in biology or genomics. 
Science can be a framework for healthy skepticisism, methods of investigation, etc.

### Practice

In general, I find that extended, long-term laboratory projects, supplemented with frequent (but brief) assessments, provide an effective learning environment for many students. 
In an introductory programming or bioinformatics course, for example, it can be helpful for students to work on a few software programs (each with a fairly large scope) throughout the course. 
Continual iteration on a single project can encourage proper version control and documentation, and it allows for frequent check-ins and "soft deadlines" while leaving room for exploration.
Students can also be periodically evaluated on basic concepts (for example, via short weekly quizzes that each contribute a small amount toward a final grade). 
This structure allows for some natural flexibility (if students need to take personal time and miss a class or two, it won't have a major effect on their final grade), and allows the professor to keep tabs on overall comprehension throughout the course.

I've also found that short, anonymous quizzes (facilitated via smartphone apps, quiz websites, or remote controls) prior to each classroom session provide a low-stakes environment for assessing comprehension throughout a course. 
Students aren't put "on the spot" and needn't worry about being docked on their final grades, and when students *do* anonymously select incorrect answers, it presents a natural (and blameless) opportunity to walk through exactly why those answers were wrong.
Similarly, I think that there's a lot of value in facilitating anonymous feedback (at the end of each week or every two weeks, for example) from students in the class.
This feedback can be about concepts that remain unclear, those that make complete sense, and suggestions about strategies I could adopt to improve the classroom experience.

When possible, I think that it's valuable to record lectures and make them available online, so that students are free to review them at their convenience.
And I always think it's important to hold one or two open-door office hours sessions per week.

As a faculty member at XXX, I'd be especially excited to teach:

### Prior experience

As a graduate student, I was a teaching assistant for a number of graduate-level courses, including **Introductory Programming for Biology** and **Applied Computational Genomics**.
I also delivered guest lectures for a Biostatistics interest group, and for a course dedicated to project management and version control.
As a member of the Data Science team at Recursion Pharmaceuticals, I mentored a number of new hires during their onboarding processes and worked with members of the Biology and Chemistry teams to develop a better understanding of software programming principles.

As a staff scientist in Aaron Quinlan's group, I worked remotely but aimed to continue mentoring students whenever possible. 
I've held biweekly "office hours" for graduate and undergraduate trainees in the lab, and have mentored prospective students during their rotation projects as well.

I've been fortunate to mentor a number of trainees throughout my career in both an academic and industry setting. 




